/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersScheduleRouteImport } from './routes/teachers-schedule'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchoolSettingsRouteImport } from './routes/school-settings'
import { Route as SchoolCurriculumRouteImport } from './routes/school-curriculum'
import { Route as ScheduleDashboardRouteImport } from './routes/schedule-dashboard'
import { Route as RtlDemoRouteImport } from './routes/rtl-demo'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PeriodsRouteImport } from './routes/periods'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConstraintsRouteImport } from './routes/constraints'
import { Route as ClassesScheduleRouteImport } from './routes/classes-schedule'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TeachersScheduleRoute = TeachersScheduleRouteImport.update({
  id: '/teachers-schedule',
  path: '/teachers-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolSettingsRoute = SchoolSettingsRouteImport.update({
  id: '/school-settings',
  path: '/school-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolCurriculumRoute = SchoolCurriculumRouteImport.update({
  id: '/school-curriculum',
  path: '/school-curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleDashboardRoute = ScheduleDashboardRouteImport.update({
  id: '/schedule-dashboard',
  path: '/schedule-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RtlDemoRoute = RtlDemoRouteImport.update({
  id: '/rtl-demo',
  path: '/rtl-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodsRoute = PeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstraintsRoute = ConstraintsRouteImport.update({
  id: '/constraints',
  path: '/constraints',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesScheduleRoute = ClassesScheduleRouteImport.update({
  id: '/classes-schedule',
  path: '/classes-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/classes-schedule': typeof ClassesScheduleRoute
  '/constraints': typeof ConstraintsRoute
  '/dashboard': typeof DashboardRoute
  '/guidance': typeof GuidanceRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/periods': typeof PeriodsRoute
  '/platform': typeof PlatformRoute
  '/rooms': typeof RoomsRoute
  '/rtl-demo': typeof RtlDemoRoute
  '/schedule-dashboard': typeof ScheduleDashboardRoute
  '/school-curriculum': typeof SchoolCurriculumRoute
  '/school-settings': typeof SchoolSettingsRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRoute
  '/teachers': typeof TeachersRoute
  '/teachers-schedule': typeof TeachersScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/classes-schedule': typeof ClassesScheduleRoute
  '/constraints': typeof ConstraintsRoute
  '/dashboard': typeof DashboardRoute
  '/guidance': typeof GuidanceRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/periods': typeof PeriodsRoute
  '/platform': typeof PlatformRoute
  '/rooms': typeof RoomsRoute
  '/rtl-demo': typeof RtlDemoRoute
  '/schedule-dashboard': typeof ScheduleDashboardRoute
  '/school-curriculum': typeof SchoolCurriculumRoute
  '/school-settings': typeof SchoolSettingsRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRoute
  '/teachers': typeof TeachersRoute
  '/teachers-schedule': typeof TeachersScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assignments': typeof AssignmentsRoute
  '/classes': typeof ClassesRoute
  '/classes-schedule': typeof ClassesScheduleRoute
  '/constraints': typeof ConstraintsRoute
  '/dashboard': typeof DashboardRoute
  '/guidance': typeof GuidanceRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/periods': typeof PeriodsRoute
  '/platform': typeof PlatformRoute
  '/rooms': typeof RoomsRoute
  '/rtl-demo': typeof RtlDemoRoute
  '/schedule-dashboard': typeof ScheduleDashboardRoute
  '/school-curriculum': typeof SchoolCurriculumRoute
  '/school-settings': typeof SchoolSettingsRoute
  '/settings': typeof SettingsRoute
  '/subjects': typeof SubjectsRoute
  '/teachers': typeof TeachersRoute
  '/teachers-schedule': typeof TeachersScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assignments'
    | '/classes'
    | '/classes-schedule'
    | '/constraints'
    | '/dashboard'
    | '/guidance'
    | '/login'
    | '/logout'
    | '/periods'
    | '/platform'
    | '/rooms'
    | '/rtl-demo'
    | '/schedule-dashboard'
    | '/school-curriculum'
    | '/school-settings'
    | '/settings'
    | '/subjects'
    | '/teachers'
    | '/teachers-schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assignments'
    | '/classes'
    | '/classes-schedule'
    | '/constraints'
    | '/dashboard'
    | '/guidance'
    | '/login'
    | '/logout'
    | '/periods'
    | '/platform'
    | '/rooms'
    | '/rtl-demo'
    | '/schedule-dashboard'
    | '/school-curriculum'
    | '/school-settings'
    | '/settings'
    | '/subjects'
    | '/teachers'
    | '/teachers-schedule'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assignments'
    | '/classes'
    | '/classes-schedule'
    | '/constraints'
    | '/dashboard'
    | '/guidance'
    | '/login'
    | '/logout'
    | '/periods'
    | '/platform'
    | '/rooms'
    | '/rtl-demo'
    | '/schedule-dashboard'
    | '/school-curriculum'
    | '/school-settings'
    | '/settings'
    | '/subjects'
    | '/teachers'
    | '/teachers-schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssignmentsRoute: typeof AssignmentsRoute
  ClassesRoute: typeof ClassesRoute
  ClassesScheduleRoute: typeof ClassesScheduleRoute
  ConstraintsRoute: typeof ConstraintsRoute
  DashboardRoute: typeof DashboardRoute
  GuidanceRoute: typeof GuidanceRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  PeriodsRoute: typeof PeriodsRoute
  PlatformRoute: typeof PlatformRoute
  RoomsRoute: typeof RoomsRoute
  RtlDemoRoute: typeof RtlDemoRoute
  ScheduleDashboardRoute: typeof ScheduleDashboardRoute
  SchoolCurriculumRoute: typeof SchoolCurriculumRoute
  SchoolSettingsRoute: typeof SchoolSettingsRoute
  SettingsRoute: typeof SettingsRoute
  SubjectsRoute: typeof SubjectsRoute
  TeachersRoute: typeof TeachersRoute
  TeachersScheduleRoute: typeof TeachersScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers-schedule': {
      id: '/teachers-schedule'
      path: '/teachers-schedule'
      fullPath: '/teachers-schedule'
      preLoaderRoute: typeof TeachersScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-settings': {
      id: '/school-settings'
      path: '/school-settings'
      fullPath: '/school-settings'
      preLoaderRoute: typeof SchoolSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-curriculum': {
      id: '/school-curriculum'
      path: '/school-curriculum'
      fullPath: '/school-curriculum'
      preLoaderRoute: typeof SchoolCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-dashboard': {
      id: '/schedule-dashboard'
      path: '/schedule-dashboard'
      fullPath: '/schedule-dashboard'
      preLoaderRoute: typeof ScheduleDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rtl-demo': {
      id: '/rtl-demo'
      path: '/rtl-demo'
      fullPath: '/rtl-demo'
      preLoaderRoute: typeof RtlDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periods': {
      id: '/periods'
      path: '/periods'
      fullPath: '/periods'
      preLoaderRoute: typeof PeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constraints': {
      id: '/constraints'
      path: '/constraints'
      fullPath: '/constraints'
      preLoaderRoute: typeof ConstraintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes-schedule': {
      id: '/classes-schedule'
      path: '/classes-schedule'
      fullPath: '/classes-schedule'
      preLoaderRoute: typeof ClassesScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssignmentsRoute: AssignmentsRoute,
  ClassesRoute: ClassesRoute,
  ClassesScheduleRoute: ClassesScheduleRoute,
  ConstraintsRoute: ConstraintsRoute,
  DashboardRoute: DashboardRoute,
  GuidanceRoute: GuidanceRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  PeriodsRoute: PeriodsRoute,
  PlatformRoute: PlatformRoute,
  RoomsRoute: RoomsRoute,
  RtlDemoRoute: RtlDemoRoute,
  ScheduleDashboardRoute: ScheduleDashboardRoute,
  SchoolCurriculumRoute: SchoolCurriculumRoute,
  SchoolSettingsRoute: SchoolSettingsRoute,
  SettingsRoute: SettingsRoute,
  SubjectsRoute: SubjectsRoute,
  TeachersRoute: TeachersRoute,
  TeachersScheduleRoute: TeachersScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
