from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="License", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("lookup_digest", models.CharField(max_length=64, unique=True)), ("key_hash", models.TextField()), ("product", models.CharField(default="desktop-timetable", max_length=64)), ("channel", models.CharField(choices=[("pilot", "Pilot"), ("stable", "Stable")], default="pilot", max_length=16)), ("enabled", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="DesktopRelease", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("channel", models.CharField(choices=[("pilot", "Pilot"), ("stable", "Stable")], max_length=16)), ("version", models.CharField(max_length=32)), ("build_id", models.CharField(max_length=128, unique=True)), ("published_at", models.DateTimeField()), ("minimum_supported_version", models.CharField(max_length=32)), ("rollout_percent", models.PositiveSmallIntegerField(default=0)), ("release_notes", models.TextField(blank=True)), ("artifact_url", models.URLField()), ("artifact_size", models.PositiveBigIntegerField()), ("artifact_sha512", models.CharField(max_length=128)), ("authenticode_publisher", models.CharField(max_length=256)), ("enabled", models.BooleanField(default=False))], options={"constraints": [models.UniqueConstraint(fields=("channel", "version"), name="unique_release_channel_version")]}),
        migrations.CreateModel(name="Activation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("device_id", models.CharField(max_length=128)), ("support_code", models.CharField(max_length=32)), ("refresh_hash", models.TextField()), ("active", models.BooleanField(default=True)), ("last_lease_id", models.UUIDField(null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("refreshed_at", models.DateTimeField(auto_now=True)), ("deactivated_at", models.DateTimeField(null=True)), ("license", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="activations", to="release.license"))], options={"constraints": [models.UniqueConstraint(condition=models.Q(("active", True)), fields=("license",), name="one_active_device_per_license")]}),
    ]
