/**
 * Property-based tests for color utilities
 * **Feature: schedule-phase4, Property 5: Color Generation Consistency (Idempotence)**
 * **Feature: schedule-phase4, Property 6: Color Contrast Accessibility**
 */

import fc from 'fast-check';
import { describe, expect, it } from 'vitest';

import { generateEntityColor, getColorLightness, getContrastTextColor } from '../utils/colorUtils';

// Generator for non-empty entity IDs (1-50 characters)
const entityIdArb = fc.string({ minLength: 1, maxLength: 50 });

// Generator for valid hex color strings
const hexColorArb = fc
  .tuple(
    fc.integer({ min: 0, max: 255 }),
    fc.integer({ min: 0, max: 255 }),
    fc.integer({ min: 0, max: 255 })
  )
  .map(([r, g, b]) => {
    const toHex = (n: number) => n.toString(16).padStart(2, '0');
    return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
  });

describe('Color Utils Property Tests', () => {
  /**
   * **Feature: schedule-phase4, Property 5: Color Generation Consistency (Idempotence)**
   * **Validates: Requirements 3.2, 3.3**
   *
   * For any entity ID string and ColorCodingMode, calling generateEntityColor with
   * the same ID SHALL always return the same color value.
   */
  it('Property 5: Same entity ID always produces the same color', () => {
    fc.assert(
      fc.property(entityIdArb, (entityId) => {
        const color1 = generateEntityColor(entityId);
        const color2 = generateEntityColor(entityId);
        const color3 = generateEntityColor(entityId);

        // All calls with the same ID should return the same color
        expect(color1).toBe(color2);
        expect(color2).toBe(color3);

        // Color should be a valid hex string
        expect(color1).toMatch(/^#[0-9a-f]{6}$/i);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * **Feature: schedule-phase4, Property 6: Color Contrast Accessibility**
   * **Validates: Requirements 3.5**
   *
   * For any color generated by generateEntityColor, the color SHALL have
   * sufficient contrast (lightness between 70-90% in HSL) to ensure text
   * readability with dark text.
   */
  it('Property 6: Generated colors have lightness in accessible range (70-90%)', () => {
    fc.assert(
      fc.property(entityIdArb, (entityId) => {
        const color = generateEntityColor(entityId);
        const lightness = getColorLightness(color);

        // Lightness should be between 70% and 90% for good contrast with dark text
        // The algorithm uses 75-85% but we allow a small margin for rounding
        expect(lightness).toBeGreaterThanOrEqual(70);
        expect(lightness).toBeLessThanOrEqual(90);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Additional property: getContrastTextColor always returns black or white
   */
  it('getContrastTextColor always returns black or white', () => {
    fc.assert(
      fc.property(hexColorArb, (backgroundColor) => {
        const textColor = getContrastTextColor(backgroundColor);

        // Should always return either black or white
        expect(['#000000', '#ffffff']).toContain(textColor);
      }),
      { numRuns: 100 }
    );
  });

  /**
   * Additional property: Different entity IDs produce valid colors
   */
  it('All generated colors are valid hex strings', () => {
    fc.assert(
      fc.property(entityIdArb, (entityId) => {
        const color = generateEntityColor(entityId);

        // Should be a valid 6-digit hex color
        expect(color).toMatch(/^#[0-9a-f]{6}$/i);

        // Should be parseable (no NaN values)
        const r = parseInt(color.substring(1, 3), 16);
        const g = parseInt(color.substring(3, 5), 16);
        const b = parseInt(color.substring(5, 7), 16);

        expect(Number.isNaN(r)).toBe(false);
        expect(Number.isNaN(g)).toBe(false);
        expect(Number.isNaN(b)).toBe(false);
      }),
      { numRuns: 100 }
    );
  });
});
