# Generated by Django 5.2.16 on 2026-08-03 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('ended', 'Ended')], default='active', max_length=20)),
                ('default_language', models.CharField(default='fa', max_length=5)),
                ('timezone', models.CharField(default='Asia/Kabul', max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('unit_type', models.CharField(choices=[('school', 'School'), ('campus', 'Campus'), ('course_center', 'Course center'), ('department', 'Department')], default='school', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tenancy.schoolunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_units', to='tenancy.tenantorganization')),
            ],
            options={
                'ordering': ['tenant__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_unit_code_per_tenant')],
            },
        ),
    ]
