# ==============================================================================
# Property Tests: Farsi Message Localization
#
# Tests for Farsi message localization in feedback messages from the solver
# and validation systems.
#
# **Feature: solver-afghanistan-features, Property 9: Farsi Message Localization**
# **Validates: Requirements 6.5**
# ==============================================================================

from typing import Dict, Any, List

import pytest
from hypothesis import given, strategies as st, settings, assume

from afghanistan.ministry_validator import (
    MinistryValidator,
    ValidationMode,
    MinistryValidationResult,
)
from afghanistan.curriculum import MINISTRY_CURRICULUM, get_grade_category


# ==============================================================================
# Custom Hypothesis Strategies
# ==============================================================================

@st.composite
def valid_class_name(draw) -> str:
    """Generate a valid class name in Farsi or English."""
    # Mix of Farsi and English class names
    names = [
        "صنف ۱-الف",
        "صنف ۲-ب",
        "صنف ۱۰-الف",
        "Class 1A",
        "Grade 5B",
        "صنف ۷",
    ]
    return draw(st.sampled_from(names))


@st.composite
def valid_grade_level(draw) -> int:
    """Generate a valid grade level (1-12)."""
    return draw(st.sampled_from(list(MINISTRY_CURRICULUM.keys())))


@st.composite
def subject_with_insufficient_periods(draw, grade: int) -> Dict[str, Any]:
    """Generate a subject requirement with insufficient periods for the grade."""
    subjects = MINISTRY_CURRICULUM[grade]
    subject = draw(st.sampled_from(subjects))
    subject_name = subject['name']
    min_periods = subject['periodsPerWeek']
    
    # Generate periods less than minimum
    configured_periods = draw(st.integers(min_value=0, max_value=max(0, min_periods - 1)))
    
    return {
        'subject_name': subject_name,
        'configured_periods': configured_periods,
        'min_periods': min_periods,
    }


@st.composite
def class_with_insufficient_subjects(draw) -> Dict[str, Any]:
    """Generate a class with at least one subject having insufficient periods."""
    grade = draw(valid_grade_level())
    class_name = draw(valid_class_name())
    class_id = f"class-{draw(st.integers(min_value=1, max_value=100))}"
    
    # Get curriculum subjects for this grade
    curriculum_subjects = MINISTRY_CURRICULUM[grade]
    category = get_grade_category(grade)
    
    # Create subject requirements with at least one insufficient
    subject_reqs = {}
    subjects = []
    
    for i, subj_info in enumerate(curriculum_subjects):
        subj_id = f"subj-{i}"
        subjects.append({
            'id': subj_id,
            'name': subj_info['name'],
        })
        
        min_periods = subj_info['periodsPerWeek']
        
        # Make at least one subject insufficient
        if i == 0:
            # First subject is always insufficient
            periods = draw(st.integers(min_value=0, max_value=max(0, min_periods - 1)))
        else:
            # Others may or may not be sufficient
            periods = draw(st.integers(min_value=0, max_value=min_periods + 2))
        
        subject_reqs[subj_id] = {'periodsPerWeek': periods}
    
    return {
        'class': {
            'id': class_id,
            'name': class_name,
            'gradeLevel': grade,
            'category': category.value if category else None,
            'subjectRequirements': subject_reqs,
        },
        'subjects': subjects,
    }


@st.composite
def solver_data_with_insufficient_class(draw) -> Dict[str, Any]:
    """Generate solver input data with at least one class having insufficient subjects."""
    class_data = draw(class_with_insufficient_subjects())
    
    return {
        'config': {
            'enableMinistryValidation': True,
            'ministryValidationMode': 'warn',
        },
        'classes': [class_data['class']],
        'subjects': class_data['subjects'],
        'teachers': [],
        'rooms': [],
    }


@st.composite
def validation_mode_enabled(draw) -> ValidationMode:
    """Generate an enabled validation mode (WARN or STRICT)."""
    return draw(st.sampled_from([ValidationMode.WARN, ValidationMode.STRICT]))


# ==============================================================================
# Property Tests: Farsi Message Localization
# ==============================================================================

class TestFarsiMessageLocalization:
    """
    **Feature: solver-afghanistan-features, Property 9: Farsi Message Localization**
    **Validates: Requirements 6.5**
    
    For any feedback message (error, warning, or suggestion) generated by the
    solver or validation system, the message SHALL include a messageFarsi field
    with a non-empty Farsi string.
    """

    @given(data=solver_data_with_insufficient_class(), mode=validation_mode_enabled())
    @settings(max_examples=100, deadline=5000)
    def test_ministry_warnings_include_farsi_message(
        self, data: Dict[str, Any], mode: ValidationMode
    ):
        """
        **Feature: solver-afghanistan-features, Property 9: Farsi Message Localization**
        **Validates: Requirements 6.5**
        
        WHEN Ministry validation generates warnings THEN each warning SHALL
        include a non-empty messageFarsi field.
        """
        validator = MinistryValidator(enabled=True, mode=mode)
        result = validator.validate(data)
        
        # Get all messages (warnings and errors)
        all_messages = result.warnings + result.errors
        
        # Assume we have at least one message (our data generator ensures this)
        assume(len(all_messages) > 0)
        
        for message in all_messages:
            # Verify messageFarsi exists and is non-empty
            assert 'messageFarsi' in message, "Message must include messageFarsi field"
            assert message['messageFarsi'] is not None, "messageFarsi must not be None"
            assert len(message['messageFarsi']) > 0, "messageFarsi must not be empty"
            
            # Verify the message contains Farsi characters (Persian/Arabic script)
            # Farsi characters are in Unicode range 0x0600-0x06FF (Arabic) and 0xFB50-0xFDFF
            has_farsi = any(
                '\u0600' <= char <= '\u06FF' or '\uFB50' <= char <= '\uFDFF'
                for char in message['messageFarsi']
            )
            assert has_farsi, f"messageFarsi must contain Farsi characters: {message['messageFarsi']}"

    @given(data=solver_data_with_insufficient_class(), mode=validation_mode_enabled())
    @settings(max_examples=100, deadline=5000)
    def test_ministry_warnings_include_english_message(
        self, data: Dict[str, Any], mode: ValidationMode
    ):
        """
        **Feature: solver-afghanistan-features, Property 9: Farsi Message Localization**
        **Validates: Requirements 6.5**
        
        WHEN Ministry validation generates warnings THEN each warning SHALL
        also include a non-empty messageEnglish field for fallback.
        """
        validator = MinistryValidator(enabled=True, mode=mode)
        result = validator.validate(data)
        
        all_messages = result.warnings + result.errors
        assume(len(all_messages) > 0)
        
        for message in all_messages:
            # Verify messageEnglish exists and is non-empty
            assert 'messageEnglish' in message, "Message must include messageEnglish field"
            assert message['messageEnglish'] is not None, "messageEnglish must not be None"
            assert len(message['messageEnglish']) > 0, "messageEnglish must not be empty"

    @given(data=solver_data_with_insufficient_class())
    @settings(max_examples=100, deadline=5000)
    def test_ministry_warnings_contain_class_and_subject_info(
        self, data: Dict[str, Any]
    ):
        """
        **Feature: solver-afghanistan-features, Property 9: Farsi Message Localization**
        **Validates: Requirements 6.5**
        
        WHEN Ministry validation generates warnings THEN the Farsi message SHALL
        contain the class name and subject name.
        """
        validator = MinistryValidator(enabled=True, mode=ValidationMode.WARN)
        result = validator.validate(data)
        
        all_messages = result.warnings + result.errors
        assume(len(all_messages) > 0)
        
        for message in all_messages:
            farsi_msg = message['messageFarsi']
            
            # Verify the message contains class name
            class_name = message.get('className', '')
            if class_name:
                assert class_name in farsi_msg, f"Farsi message should contain class name '{class_name}'"
            
            # Verify the message contains subject name
            subject_name = message.get('subjectName', '')
            if subject_name:
                assert subject_name in farsi_msg, f"Farsi message should contain subject name '{subject_name}'"

    @given(data=solver_data_with_insufficient_class())
    @settings(max_examples=100, deadline=5000)
    def test_ministry_warnings_contain_period_counts(
        self, data: Dict[str, Any]
    ):
        """
        **Feature: solver-afghanistan-features, Property 9: Farsi Message Localization**
        **Validates: Requirements 6.5**
        
        WHEN Ministry validation generates warnings THEN the Farsi message SHALL
        contain the required and configured period counts.
        """
        validator = MinistryValidator(enabled=True, mode=ValidationMode.WARN)
        result = validator.validate(data)
        
        all_messages = result.warnings + result.errors
        assume(len(all_messages) > 0)
        
        for message in all_messages:
            farsi_msg = message['messageFarsi']
            msg_type = message.get('type', '')
            
            if msg_type == 'MINISTRY_SUBJECT_HOURS':
                required = message.get('requiredPeriods', 0)
                configured = message.get('configuredPeriods', 0)
                # Verify the message contains period counts
                assert str(required) in farsi_msg, f"Farsi message should contain required periods '{required}'"
                assert str(configured) in farsi_msg, f"Farsi message should contain configured periods '{configured}'"
            elif msg_type == 'TOTAL_PERIODS_MISMATCH':
                expected = message.get('expectedPeriods', 0)
                actual = message.get('actualPeriods', 0)
                # Verify the message contains period counts
                assert str(expected) in farsi_msg, f"Farsi message should contain expected periods '{expected}'"
                assert str(actual) in farsi_msg, f"Farsi message should contain actual periods '{actual}'"

    @given(data=solver_data_with_insufficient_class())
    @settings(max_examples=100, deadline=5000)
    def test_strict_mode_errors_have_farsi_messages(
        self, data: Dict[str, Any]
    ):
        """
        **Feature: solver-afghanistan-features, Property 9: Farsi Message Localization**
        **Validates: Requirements 6.5**
        
        WHEN Ministry validation in strict mode generates errors THEN each error
        SHALL include a non-empty messageFarsi field.
        """
        validator = MinistryValidator(enabled=True, mode=ValidationMode.STRICT)
        result = validator.validate(data)
        
        # In strict mode, issues become errors
        assume(len(result.errors) > 0)
        
        for error in result.errors:
            assert 'messageFarsi' in error, "Error must include messageFarsi field"
            assert error['messageFarsi'] is not None, "messageFarsi must not be None"
            assert len(error['messageFarsi']) > 0, "messageFarsi must not be empty"
            
            # Verify Farsi characters present
            has_farsi = any(
                '\u0600' <= char <= '\u06FF' or '\uFB50' <= char <= '\uFDFF'
                for char in error['messageFarsi']
            )
            assert has_farsi, f"messageFarsi must contain Farsi characters: {error['messageFarsi']}"


# ==============================================================================
# Property Tests: Message Consistency
# ==============================================================================

class TestMessageConsistency:
    """
    Tests for consistency between Farsi and English messages.
    """

    @given(data=solver_data_with_insufficient_class())
    @settings(max_examples=100, deadline=5000)
    def test_farsi_and_english_messages_convey_same_info(
        self, data: Dict[str, Any]
    ):
        """
        **Feature: solver-afghanistan-features, Property 9: Farsi Message Localization**
        **Validates: Requirements 6.5**
        
        WHEN messages are generated THEN the Farsi and English versions SHALL
        convey the same information (same period counts).
        """
        validator = MinistryValidator(enabled=True, mode=ValidationMode.WARN)
        result = validator.validate(data)
        
        all_messages = result.warnings + result.errors
        assume(len(all_messages) > 0)
        
        for message in all_messages:
            farsi_msg = message['messageFarsi']
            english_msg = message['messageEnglish']
            msg_type = message.get('type', '')
            
            if msg_type == 'MINISTRY_SUBJECT_HOURS':
                required = str(message.get('requiredPeriods', 0))
                configured = str(message.get('configuredPeriods', 0))
                # Both messages should contain the same period counts
                assert required in farsi_msg, "Farsi message should contain required periods"
                assert required in english_msg, "English message should contain required periods"
                assert configured in farsi_msg, "Farsi message should contain configured periods"
                assert configured in english_msg, "English message should contain configured periods"
            elif msg_type == 'TOTAL_PERIODS_MISMATCH':
                expected = str(message.get('expectedPeriods', 0))
                actual = str(message.get('actualPeriods', 0))
                # Both messages should contain the same period counts
                assert expected in farsi_msg, "Farsi message should contain expected periods"
                assert expected in english_msg, "English message should contain expected periods"
                assert actual in farsi_msg, "Farsi message should contain actual periods"
                assert actual in english_msg, "English message should contain actual periods"

    @given(data=solver_data_with_insufficient_class(), mode=validation_mode_enabled())
    @settings(max_examples=100, deadline=5000)
    def test_message_severity_matches_mode(
        self, data: Dict[str, Any], mode: ValidationMode
    ):
        """
        **Feature: solver-afghanistan-features, Property 9: Farsi Message Localization**
        **Validates: Requirements 6.5**
        
        WHEN messages are generated THEN the severity SHALL match the validation mode.
        In strict mode:
          - Core subjects produce errors
          - TOTAL_PERIODS_MISMATCH produces errors
          - Non-core subjects produce warnings
        In warn mode, all issues produce warnings.
        """
        validator = MinistryValidator(enabled=True, mode=mode)
        result = validator.validate(data)
        
        all_messages = result.warnings + result.errors
        assume(len(all_messages) > 0)
        
        for message in all_messages:
            msg_type = message.get('type', '')
            is_core = message.get('isCore', False)
            
            if mode == ValidationMode.STRICT:
                # In strict mode: core subjects and total mismatch are errors
                if is_core or msg_type == 'TOTAL_PERIODS_MISMATCH':
                    assert message['severity'] == 'error', f"Strict mode should produce errors for core subjects and total mismatch"
                else:
                    assert message['severity'] == 'warning', "Non-core subjects should produce warnings"
            else:
                # In warn mode, all issues are warnings
                assert message['severity'] == 'warning', "Warn mode should produce warnings"
